name: easy-busboy package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        default: 'debug'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: https://npm.pkg.github.com/
      - run: pnpm ci
      - run: pnpm test
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
